In [1]:
# 스칼라(scalar)

# 스칼라는 정수나 실수와 같은 상수를 나타낸다고 이해하면 쉽다. 
# 양을 나타내지만,방향성을 갖지는 않는다. 따라서, 벡터가 존재하지 않기때문에 차수가 0이된다.
# 텐서플로에서는 '랭크(rank)-0' 텐서라고 부른다. 랭크는 텐서의 차수를 나타낸다.
# 스칼라는 벡터가 없는 0차원으로 표현되므로 랭크-0텐서라고 정의한다.
# 스칼라 텐서는 constant함수에 상수값을 입력해 만들수있다
# 여기서 배열의 크기를 나타낸는 shape=() 값을 보면,
# 배열을 나타내는 값이 존재하지않기 때문에,0차원이라고 보면 된다.

In [2]:
import tensorflow as tf

a = tf.constant(1)
b = tf.constant(2)
print('a:', a)
print('b:', b)

a: tf.Tensor(1, shape=(), dtype=int32)
b: tf.Tensor(2, shape=(), dtype=int32)


In [3]:
# cast() 함수 - 텐서의 자료형을 변환하고 싶을때 사용한다.
###텐서플로 딥러닝연산에서는 float32를 기본 숫자형 데이터 형식로 사용된다.

a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)

print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [4]:
# math 모듈 - 여러가지 수학함수 정의

# 덧셈(add)
c = tf.math.add(a, b)
print('result:', c)
print('rank:', tf.rank(c))

result: tf.Tensor(3.0, shape=(), dtype=float32)
rank: tf.Tensor(0, shape=(), dtype=int32)


In [5]:
# 뺄셈(subtract)
print(tf.math.subtract(a,b))

tf.Tensor(-1.0, shape=(), dtype=float32)


In [6]:
# 곱셈(multiply)
print(tf.math.multiply(a,b))

tf.Tensor(2.0, shape=(), dtype=float32)


In [7]:
# 나눗셈(divide)
print(tf.math.divide(a,b))

tf.Tensor(0.5, shape=(), dtype=float32)


In [9]:
# 나눗셈(나머지)(mod)
print(tf.math.mod(a,b))
# 나눗셈(몫)(floordiv)
print(tf.math.floordiv(a,b))

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


In [ ]:
# 벡터(vector)

# 벡터는 여러 개의 스칼라 값을 원소로 갖는 1차원 배열로 표현된다. 스칼라 여러개가 동일한 축 방향으로 나열되는 개념이다.
# 벡터는 원소로 구성되는 여러개의 값들이 모여서 하나의 대표성을 갖는 값이 된다.
# 좌표계 공간으로 표현하면 어떤방향으로 크기를 갖는다.
# 따라서 각 원소값의 크기뿐만 아니라, 원소들이 나열되는 순서에도 의미가 있다.
# 원소가 되는 10,20,30은 각각 스칼라이고 이들이 모여서 1차원 텐서인 벡터가 된다
# 벡터는 하나의 축을 갖기 떄문에 차수가 1이고, 랭크-1 텐서라고 부른다
# constant함수에 1차원 배열을 입력하면 1차원 텐서인 벡터로 변환된다.
# 함수의 입력값으로 파이썬 list와 numpy array를 모두 사용할수있다.
# 벡터의 shape속성은 ( 원소개수,  ) 형태로 표현된다.

In [10]:
import tensorflow as tf
import numpy as np

py_list = [10., 20., 30.]
num_arr = np.array([10.,10.,10])

vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

print('vec1:', vec1)
print('vec2:', vec2)

vec1: tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
vec2: tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [11]:
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# tf.math 모듈의 add함수로 덧셈연산처리 
# =>이때 같은 위치에 있는 원소들끼리(element-by-element) 짝을 이루어서 계산한다.

add1 = tf.math.add(vec1,vec2)
print('result:', add1)
print('rank:', tf.rank(add1))

result: tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
# 벡터를 구성하는 원소들의 합계 구하기 - reduce_sum 함수

print(tf.reduce_sum(vec1))
print(tf.reduce_sum(vec2))

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)


In [14]:
# 거듭제곱 -math 모듈의 square 함수
# =>각 원소를 거듭제곱한 결과를 벡터로 반환.

print(tf.math.square(vec1))

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [ ]:
# 행렬(matrix)

# 행렬은 차수가 1이니 벡터를 같은 축 방향으로 나열하는 개념이다. 여러개의 1차원 벡터를 원소로 갖는 1차원 배열이다.
# 원소의 차수가 1이므로 총 차수는 2이다. 텐서플로에서는 '랭크-2'텐서라고 부른다.
# 리스트를 원소로 갖는 리스트를 사용하여 입력값으로 전달한다. => [[10,20],[30,40]]


In [15]:
import tensorflow as tf

list_of_list = [[10,20],[30,40]]

mat1 = tf.constant(list_of_list)

print('rank:', tf.rank(mat1))
print('mat:', mat1)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat: tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [16]:
# stack 함수를 사용하여 행렬 만들기
vec1 = tf.constant([1,0])
vec2 = tf.constant([-1,2])

mat2 = tf.stack([vec1,vec2])

print('rank:', tf.rank(mat2))

print('mat2:',mat2)

rank: tf.Tensor(2, shape=(), dtype=int32)
mat2: tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [17]:
# element-by-element연산과 행렬곱연산

element_mul = tf.math.multiply(mat1,mat2)
print('result:', element_mul)
print('rank:', tf.rank(element_mul))

element_bc = tf.math.multiply(mat1, 3)
print('result:', element_bc)
print('rank:', tf.rank(element_bc))

result: tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)
result: tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [18]:
mat_mul = tf.matmul(mat1,mat2)
print('result:', mat_mul)
print('rank:', tf.rank(mat_mul))

result: tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank: tf.Tensor(2, shape=(), dtype=int32)


In [19]:
# 텐서를 넘파이배열로 변환
np_arr = mat_mul.numpy()
print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]


In [21]:
# 고차원 텐서(tensor)

import tensorflow as tf
import numpy as np

mat1 = [[1,2,3,4],
        [5,6,7,8]]

mat2 = [[9,10,11,12],
        [13,14,15,16]]

mat3 = [[17,18,19,20],
        [21,22,23,24]]

tensor1 = tf.constant([mat1,mat2,mat3])
print('rank:', tf.rank(tensor1))
print('tensor1:', tensor1)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor1: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [24]:
tensor2 = tf.stack([mat1,mat2,mat3])

print('rank:', tf.rank(tensor2))
print('tesnsor2:',tensor2)

rank: tf.Tensor(3, shape=(), dtype=int32)
tesnsor2: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [25]:
vec1 = [1,2,3,4]
vec2 = [5,6,7,8]
vec3 = [9,10,11,12]
vec4 = [13,14,15,16]
vec5 = [17,18,19,20]
vec6 = [21,22,23,24]

arr = [[vec1,vec2],
       [vec3,vec4],
       [vec5,vec6]]

tensor3 = tf.constant(arr)

print('rank:', tf.rank(tensor3))
print('tensor3:',tensor3)

rank: tf.Tensor(3, shape=(), dtype=int32)
tensor3: tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [27]:
tensor4 = tf.stack([tensor1, tensor2])

print('rank:', tf.rank(tensor4))
print('tesnor:', tensor4)

rank: tf.Tensor(4, shape=(), dtype=int32)
tesnor: tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)
