In [ ]:
# 변수(tf.Variable)
# 텐서플로를 활용하여 딥러닝 모델을 만들고 학습할때, 텐서플로 변수를 놓고 활용하면 정교하게 연산을 제어할수있다.
# 특히 딥러닝 모델의 가중치와 학습률 처럼 모델학습 및 추론과정에서 값이 면경되는경우 변수를 활용한다.

# 텐서플로는 그래프구조를 이용하여 복잡한 미분연산을 한다. 
# 이때 수많은 미분연산을 반복하게 되는데, 각각의 중간 연산결과를 저장할때 변수를 이용한다. 
# 모델을 학습하는 중간단계마다 모델의 가중치 행렬을 변수에 저장하고, 계산을 반복하면서 변수의 값을 업데이트한다.

# 또한, 최적화 알고리즘을 적용할 때, 모델의 학습률을 저장하는데에도 사용된다.
# 최적화란 모델에 적용되는 학습률을 조금씩 바꾸면서 최적의 결과를 찾는 과정을 말한다.
# 이때 변수는 변화하는 학습률값을 저장하게된다.


In [3]:
import tensorflow as tf
import numpy as np

tensor1 = tf.constant([[0,1,2],
                       [3,4,5]])

print(tensor1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [4]:
tensor_var1 = tf.Variable(tensor1)
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>


In [5]:
print('이름:',tensor_var1.name)
print('크기:',tensor_var1.shape)
print('자료형:',tensor_var1.dtype)
print('배열:', tensor_var1.numpy())

이름: Variable:0
크기: (2, 3)
자료형: <dtype: 'int32'>
배열: [[0 1 2]
 [3 4 5]]


In [6]:
tensor_var1.assign([[1,1,1],[2,2,2]])

print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>


In [7]:
tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [8]:
tensor_var2 = tf.Variable(tensor2, name='New Name')
print(tensor_var2.name)

New Name:0


In [9]:
tensor_var1 + tensor_var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]])>

In [ ]:
# 자동 미분(Automatic Differentiation)

# 텐서플로는 딥러닝 모델을 구성하는 복잡하는 인공신경망의 각 노드에서 계산되는 미분을 자동으로 계산해준다
# 특히 각 변수의 기울기에 해당하는 그래디언트를 계산하는데 특화되어있다.

In [11]:
import tensorflow as tf
g = tf.random.Generator.from_seed(2020)
X = g.normal(shape=(10, ))
Y = 3*X - 2

print('X:', X.numpy())
print('Y:', Y.numpy())

X: [-0.20943771  1.2746525   1.213214   -0.17576952  1.876984    0.16379918
  1.082245    0.6199966  -0.44402212  1.3048344 ]
Y: [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086024
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]


In [12]:
# Loss 함수 정의
def cal_mse(X, Y, a, b):

    Y_pred = a*X + b
    squared_error = (Y_pred - Y) ** 2
    mean_squared_error = tf.reduce_mean(squared_error)

    return mean_squared_error

In [13]:
# tf.GradientTape로 자동 미분 과정을 기록

a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS+1) :
    with tf.GradientTape() as tape :
        mse = cal_mse(X, Y, a, b)

    grad = tape.gradient(mse,{'a':a,'b':b})
    d_a, d_b = grad['a'], grad['b']

    a.assign_sub(d_a * 0.05) 
    b.assign_sub(d_b * 0.05)

    if epoch % 20 == 0 :
        print("EPOCH %d - MSE: %4f ---a:%.2f ---b:%.2f" %(epoch, mse, a, b))

EPOCH 20 - MSE: 1.141489 ---a:1.74 ---b:-0.75
EPOCH 40 - MSE: 0.288145 ---a:2.37 ---b:-1.37
EPOCH 60 - MSE: 0.072789 ---a:2.69 ---b:-1.68
EPOCH 80 - MSE: 0.018387 ---a:2.84 ---b:-1.84
EPOCH 100 - MSE: 0.004645 ---a:2.92 ---b:-1.92
EPOCH 120 - MSE: 0.001173 ---a:2.96 ---b:-1.96
EPOCH 140 - MSE: 0.000296 ---a:2.98 ---b:-1.98
EPOCH 160 - MSE: 0.000075 ---a:2.99 ---b:-1.99
EPOCH 180 - MSE: 0.000019 ---a:2.99 ---b:-1.99
EPOCH 200 - MSE: 0.000005 ---a:3.00 ---b:-2.00
