In [1]:
import tensorflow as tf

vec = tf.constant([10,20,30,40,50])
print(vec)

print(vec[0])

print(vec[-1])

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)


In [ ]:
print(vec[:3])

In [2]:
mat = tf.constant([[10,20,30],
                   [40,50,60]])

print(mat[0,2])

tf.Tensor(30, shape=(), dtype=int32)


In [3]:
print(mat[0,:])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [4]:
print(mat[:,1])

tf.Tensor([20 50], shape=(2,), dtype=int32)


In [5]:
print(mat[:,:])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [6]:
tensor = tf.constant([
    [[10,20,30],
     [40,50,60]],
    [[-10,-20,-30],
     [-40,-50,-60]]
])

print(tensor)

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)


In [7]:
print(tensor[0,:,:])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [8]:
print(tensor[:,:2,:2])

tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)


In [1]:
import tensorflow as tf

tensor = tf.constant(range(0,24))
print(tensor)


tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [2]:
tensor1 = tf.reshape(tensor,[3,8])
print(tensor1)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)


In [3]:
tensor2 = tf.reshape(tensor1,[-1,4])
print(tensor2)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)


In [4]:
tensor3 = tf.reshape(tensor2,[-1])
print(tensor3)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [5]:
tensor4 = tf.reshape(tensor3,[-1,3,4])
print(tensor4)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [6]:
tensor5 = tf.reshape(tensor4,[3,2,4])
print(tensor5)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)


In [7]:
tensor6 = tf.reshape(tensor5, [3,2,2,2])
print(tensor6)

tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(3, 2, 2, 2), dtype=int32)
